apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: hello-app-hurl
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/WitoDelnat/testkube-poc
      revision: main
      paths:
        - tests
  steps:
    - name: Run test
      run:
        image: ghcr.io/orange-opensource/hurl:4.2.0
